### ISSUE TITLE
Error while setting up project

### ISSUE THREAD

**Issue by mkucharz** [eyedea-io/webmaster-kit#6]
This is what I'm getting now:
```
? CircleCI token(https://circleci.com/account/api) <token>
? GitHub token(https://github.com/settings/tokens/new - repo, read:user) <token>
? Select GitHub account mkucharz
? GitHub repository name syncano-component-example
? Private repository No
? Syncano instance name component-example
✔ Created repository on your account.
ERROR: Failed to attach remote.
Error: Error: Command failed: git commit -m "chore: initial commit"

    at /Users/qk/syncano-component-example/.config/setup.js:302:23
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Failed to initialize webmaster kit.
Error: Error: Command failed: git commit -m "chore: initial commit"

    at /Users/qk/syncano-component-example/.config/setup.js:302:23
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by Idered** [comment]
Now .git is removed when eyedea-io/webmaster-kit is set as origin. If it's set to anything else it won't be removed and will cause that error. I guess we should ask if user wants to remove .git
